vehicle:
  mass_kg: 1000
  g: 9.81
  Crr: 0.07
aero:
  rho: 2.0
  Cd: 1.1
  Cl: 1.5
  A: 1.0
tyre:
  mu: 1.6
powertrain:
  P_max_kW: 80
  Fx_max_N: 3900
battery:
  capacity_kWh: 2
  initial_soc: 1.0
  min_soc: 0.1
  max_discharge_kW: 80
  eta_discharge: 0.95
  enabled: true
